FROM apache/airflow:2.9.1-python3.11

# Install DataGate dependencies
RUN pip install --no-cache-dir \
    yfinance \
    requests \
    pandas \
    boto3==1.34.0 \
    duckdb==0.10.3 \
    dbt-core==1.8.0 \
    dbt-duckdb==1.8.0 \
    google-genai \
    openai \
    python-dotenv \
    loguru \
    tenacity \
    arrow \
    beautifulsoup4 \
    pydantic==2.6.4 \
    kafka-python==2.0.2 \
    "pyOpenSSL==23.2.0" \
    "cryptography==41.0.7" \
    dbt-core==1.8.0 \
    dbt-duckdb==1.8.0