finpulse:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /opt/datagate/duckdb/datagate.db
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
